-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 22:22:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Autismo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Autismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Autismo` DEFAULT CHARACTER SET utf8 ;
USE `Autismo` ;

-- -----------------------------------------------------
-- Table `Autismo`.`Analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Analisis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `areaSocial` INT NULL,
  `areaLinguistica` INT NULL,
  `areaConductas` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Persona` (
  `usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NULL,
  `Login_usuario` VARCHAR(45) NOT NULL,
  `cont` VARCHAR(45) NOT NULL,
  `Analisis_id` INT NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_Persona_Analisis1_idx` (`Analisis_id` ASC),
  CONSTRAINT `fk_Persona_Analisis1`
    FOREIGN KEY (`Analisis_id`)
    REFERENCES `Autismo`.`Analisis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `Autismo`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Cuenta` (
  `id` INT NOT NULL,
  `Persona_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cuenta_Persona1_idx` (`Persona_usuario` ASC),
  CONSTRAINT `fk_Cuenta_Persona1`
    FOREIGN KEY (`Persona_usuario`)
    REFERENCES `Autismo`.`Persona` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Pictograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Pictograma` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` BLOB NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Cuenta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pictograma_Categoria_idx` (`Categoria_id` ASC),
  INDEX `fk_Pictograma_Cuenta1_idx` (`Cuenta_id` ASC),
  CONSTRAINT `fk_Pictograma_Categoria`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `Autismo`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pictograma_Cuenta1`
    FOREIGN KEY (`Cuenta_id`)
    REFERENCES `Autismo`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Persona;
insert into Analisis values (0, 1,2,3);
insert into Persona values
 ("Avc", "Pedro","Ramirez", "qe", 23, "asda", "ada", "afa", 0); 