-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 21:25:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Autismo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Autismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Autismo` DEFAULT CHARACTER SET utf8 ;
USE `Autismo` ;

-- -----------------------------------------------------
-- Table `Autismo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Usuario` (
  `usuario` VARCHAR(45) NOT NULL,
  `contra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Analisis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `areaSocial` INT NULL,
  `areaLinguistica` INT NULL,
  `areaConductas` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Persona` (
  `nombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NULL,
  `Login_usuario` VARCHAR(45) NOT NULL,
  `Analisis_id` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Usuario_Login1_idx` (`Login_usuario` ASC),
  INDEX `fk_Usuario_Analisis1_idx` (`Analisis_id` ASC),
  CONSTRAINT `fk_Usuario_Login1`
    FOREIGN KEY (`Login_usuario`)
    REFERENCES `Autismo`.`Usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Analisis1`
    FOREIGN KEY (`Analisis_id`)
    REFERENCES `Autismo`.`Analisis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `Autismo`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Cuenta` (
  `id` INT NOT NULL,
  `Usuario_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cuenta_Usuario1_idx` (`Usuario_nombre` ASC),
  CONSTRAINT `fk_Cuenta_Usuario1`
    FOREIGN KEY (`Usuario_nombre`)
    REFERENCES `Autismo`.`Persona` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autismo`.`Pictograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autismo`.`Pictograma` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` BLOB NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Cuenta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pictograma_Categoria_idx` (`Categoria_id` ASC),
  INDEX `fk_Pictograma_Cuenta1_idx` (`Cuenta_id` ASC),
  CONSTRAINT `fk_Pictograma_Categoria`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `Autismo`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pictograma_Cuenta1`
    FOREIGN KEY (`Cuenta_id`)
    REFERENCES `Autismo`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
